linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: git-vendor
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - misspell
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
