version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*os.File).Close
    govet:
      disable:
        - shadow
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - commentedOutCode
        - unnamedResult
        - octalLiteral
        - appendCombine
        - httpNoBody
        - regexpSimplify
    revive:
      rules:
        - name: exported
          severity: warning
        - name: unused-parameter
          severity: warning

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
