version: 2

linters-settings:
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow      # Too strict - common pattern
      - fieldalignment  # Micro-optimization, not worth the code churn
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - commentedOutCode  # Commented code is sometimes intentional
      - unnamedResult     # Named results not always clearer
      - octalLiteral      # 0755 vs 0o755 is stylistic
      - appendCombine     # Sometimes clearer to append separately
      - httpNoBody        # Stylistic preference
      - regexpSimplify    # Subjective improvement
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional quality linters
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
    - text: "stutters"
      linters:
        - revive
    - text: "avoid meaningless package names"
      linters:
        - revive
    # Exclude errcheck for UI/TUI code where errors are not critical
    - path: internal/tui/
      text: "Error return value.*is not checked"
      linters:
        - errcheck
    # Exclude errcheck for main.go CLI output formatting
    - path: main\.go
      text: "Error return value of.*FormatJSON.*is not checked"
      linters:
        - errcheck

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
