linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional quality linters
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
    - text: "stutters"
      linters:
        - revive
    - text: "avoid meaningless package names"
      linters:
        - revive

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
