// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/github_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLicenseChecker is a mock of LicenseChecker interface.
type MockLicenseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseCheckerMockRecorder
}

// MockLicenseCheckerMockRecorder is the mock recorder for MockLicenseChecker.
type MockLicenseCheckerMockRecorder struct {
	mock *MockLicenseChecker
}

// NewMockLicenseChecker creates a new mock instance.
func NewMockLicenseChecker(ctrl *gomock.Controller) *MockLicenseChecker {
	mock := &MockLicenseChecker{ctrl: ctrl}
	mock.recorder = &MockLicenseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLicenseChecker) EXPECT() *MockLicenseCheckerMockRecorder {
	return m.recorder
}

// CheckLicense mocks base method.
func (m *MockLicenseChecker) CheckLicense(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLicense", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLicense indicates an expected call of CheckLicense.
func (mr *MockLicenseCheckerMockRecorder) CheckLicense(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLicense", reflect.TypeOf((*MockLicenseChecker)(nil).CheckLicense), url)
}

// IsAllowed mocks base method.
func (m *MockLicenseChecker) IsAllowed(license string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAllowed", license)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAllowed indicates an expected call of IsAllowed.
func (mr *MockLicenseCheckerMockRecorder) IsAllowed(license interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockLicenseChecker)(nil).IsAllowed), license)
}
