// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/lock_store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	types "git-vendor/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLockStore is a mock of LockStore interface.
type MockLockStore struct {
	ctrl     *gomock.Controller
	recorder *MockLockStoreMockRecorder
}

// MockLockStoreMockRecorder is the mock recorder for MockLockStore.
type MockLockStoreMockRecorder struct {
	mock *MockLockStore
}

// NewMockLockStore creates a new mock instance.
func NewMockLockStore(ctrl *gomock.Controller) *MockLockStore {
	mock := &MockLockStore{ctrl: ctrl}
	mock.recorder = &MockLockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockStore) EXPECT() *MockLockStoreMockRecorder {
	return m.recorder
}

// GetHash mocks base method.
func (m *MockLockStore) GetHash(vendorName, ref string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHash", vendorName, ref)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHash indicates an expected call of GetHash.
func (mr *MockLockStoreMockRecorder) GetHash(vendorName, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockLockStore)(nil).GetHash), vendorName, ref)
}

// Load mocks base method.
func (m *MockLockStore) Load() (types.VendorLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(types.VendorLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockLockStoreMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockLockStore)(nil).Load))
}

// Path mocks base method.
func (m *MockLockStore) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockLockStoreMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockLockStore)(nil).Path))
}

// Save mocks base method.
func (m *MockLockStore) Save(lock types.VendorLock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", lock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLockStoreMockRecorder) Save(lock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLockStore)(nil).Save), lock)
}
