// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/git_operations.go

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"

	types "github.com/EmundoT/git-vendor/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockGitClient is a mock of GitClient interface.
type MockGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitClientMockRecorder
}

// MockGitClientMockRecorder is the mock recorder for MockGitClient.
type MockGitClientMockRecorder struct {
	mock *MockGitClient
}

// NewMockGitClient creates a new mock instance.
func NewMockGitClient(ctrl *gomock.Controller) *MockGitClient {
	mock := &MockGitClient{ctrl: ctrl}
	mock.recorder = &MockGitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitClient) EXPECT() *MockGitClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockGitClient) Add(ctx context.Context, dir string, paths ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, dir}
	for _, a := range paths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockGitClientMockRecorder) Add(ctx, dir interface{}, paths ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, dir}, paths...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockGitClient)(nil).Add), varargs...)
}

// AddNote mocks base method.
func (m *MockGitClient) AddNote(ctx context.Context, dir, noteRef, commitHash, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNote", ctx, dir, noteRef, commitHash, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNote indicates an expected call of AddNote.
func (mr *MockGitClientMockRecorder) AddNote(ctx, dir, noteRef, commitHash, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNote", reflect.TypeOf((*MockGitClient)(nil).AddNote), ctx, dir, noteRef, commitHash, content)
}

// AddRemote mocks base method.
func (m *MockGitClient) AddRemote(ctx context.Context, dir, name, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemote", ctx, dir, name, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemote indicates an expected call of AddRemote.
func (mr *MockGitClientMockRecorder) AddRemote(ctx, dir, name, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemote", reflect.TypeOf((*MockGitClient)(nil).AddRemote), ctx, dir, name, url)
}

// Checkout mocks base method.
func (m *MockGitClient) Checkout(ctx context.Context, dir, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, dir, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockGitClientMockRecorder) Checkout(ctx, dir, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockGitClient)(nil).Checkout), ctx, dir, ref)
}

// Clone mocks base method.
func (m *MockGitClient) Clone(ctx context.Context, dir, url string, opts *types.CloneOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", ctx, dir, url, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockGitClientMockRecorder) Clone(ctx, dir, url, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockGitClient)(nil).Clone), ctx, dir, url, opts)
}

// Commit mocks base method.
func (m *MockGitClient) Commit(ctx context.Context, dir string, opts types.CommitOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, dir, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockGitClientMockRecorder) Commit(ctx, dir, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockGitClient)(nil).Commit), ctx, dir, opts)
}

// Fetch mocks base method.
func (m *MockGitClient) Fetch(ctx context.Context, dir string, depth int, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, dir, depth, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockGitClientMockRecorder) Fetch(ctx, dir, depth, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockGitClient)(nil).Fetch), ctx, dir, depth, ref)
}

// FetchAll mocks base method.
func (m *MockGitClient) FetchAll(ctx context.Context, dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockGitClientMockRecorder) FetchAll(ctx, dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockGitClient)(nil).FetchAll), ctx, dir)
}

// GetCommitLog mocks base method.
func (m *MockGitClient) GetCommitLog(ctx context.Context, dir, oldHash, newHash string, maxCount int) ([]types.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitLog", ctx, dir, oldHash, newHash, maxCount)
	ret0, _ := ret[0].([]types.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitLog indicates an expected call of GetCommitLog.
func (mr *MockGitClientMockRecorder) GetCommitLog(ctx, dir, oldHash, newHash, maxCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitLog", reflect.TypeOf((*MockGitClient)(nil).GetCommitLog), ctx, dir, oldHash, newHash, maxCount)
}

// GetHeadHash mocks base method.
func (m *MockGitClient) GetHeadHash(ctx context.Context, dir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadHash", ctx, dir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadHash indicates an expected call of GetHeadHash.
func (mr *MockGitClientMockRecorder) GetHeadHash(ctx, dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadHash", reflect.TypeOf((*MockGitClient)(nil).GetHeadHash), ctx, dir)
}

// GetNote mocks base method.
func (m *MockGitClient) GetNote(ctx context.Context, dir, noteRef, commitHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, dir, noteRef, commitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockGitClientMockRecorder) GetNote(ctx, dir, noteRef, commitHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockGitClient)(nil).GetNote), ctx, dir, noteRef, commitHash)
}

// GetTagForCommit mocks base method.
func (m *MockGitClient) GetTagForCommit(ctx context.Context, dir, commitHash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagForCommit", ctx, dir, commitHash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagForCommit indicates an expected call of GetTagForCommit.
func (mr *MockGitClientMockRecorder) GetTagForCommit(ctx, dir, commitHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagForCommit", reflect.TypeOf((*MockGitClient)(nil).GetTagForCommit), ctx, dir, commitHash)
}

// Init mocks base method.
func (m *MockGitClient) Init(ctx context.Context, dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx, dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockGitClientMockRecorder) Init(ctx, dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockGitClient)(nil).Init), ctx, dir)
}

// ListTree mocks base method.
func (m *MockGitClient) ListTree(ctx context.Context, dir, ref, subdir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTree", ctx, dir, ref, subdir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTree indicates an expected call of ListTree.
func (mr *MockGitClientMockRecorder) ListTree(ctx, dir, ref, subdir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTree", reflect.TypeOf((*MockGitClient)(nil).ListTree), ctx, dir, ref, subdir)
}
