// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/git_operations.go

// Package core is a generated GoMock package.
package core

import (
	reflect "reflect"

	types "github.com/EmundoT/git-vendor/internal/types"
	gomock "github.com/golang/mock/gomock"
)

// MockGitClient is a mock of GitClient interface.
type MockGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitClientMockRecorder
}

// MockGitClientMockRecorder is the mock recorder for MockGitClient.
type MockGitClientMockRecorder struct {
	mock *MockGitClient
}

// NewMockGitClient creates a new mock instance.
func NewMockGitClient(ctrl *gomock.Controller) *MockGitClient {
	mock := &MockGitClient{ctrl: ctrl}
	mock.recorder = &MockGitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitClient) EXPECT() *MockGitClientMockRecorder {
	return m.recorder
}

// AddRemote mocks base method.
func (m *MockGitClient) AddRemote(dir, name, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemote", dir, name, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemote indicates an expected call of AddRemote.
func (mr *MockGitClientMockRecorder) AddRemote(dir, name, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemote", reflect.TypeOf((*MockGitClient)(nil).AddRemote), dir, name, url)
}

// Checkout mocks base method.
func (m *MockGitClient) Checkout(dir, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", dir, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockGitClientMockRecorder) Checkout(dir, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockGitClient)(nil).Checkout), dir, ref)
}

// Clone mocks base method.
func (m *MockGitClient) Clone(dir, url string, opts *types.CloneOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", dir, url, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockGitClientMockRecorder) Clone(dir, url, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockGitClient)(nil).Clone), dir, url, opts)
}

// Fetch mocks base method.
func (m *MockGitClient) Fetch(dir string, depth int, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", dir, depth, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockGitClientMockRecorder) Fetch(dir, depth, ref interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockGitClient)(nil).Fetch), dir, depth, ref)
}

// FetchAll mocks base method.
func (m *MockGitClient) FetchAll(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockGitClientMockRecorder) FetchAll(dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockGitClient)(nil).FetchAll), dir)
}

// GetCommitLog mocks base method.
func (m *MockGitClient) GetCommitLog(dir, oldHash, newHash string, maxCount int) ([]types.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitLog", dir, oldHash, newHash, maxCount)
	ret0, _ := ret[0].([]types.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitLog indicates an expected call of GetCommitLog.
func (mr *MockGitClientMockRecorder) GetCommitLog(dir, oldHash, newHash, maxCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitLog", reflect.TypeOf((*MockGitClient)(nil).GetCommitLog), dir, oldHash, newHash, maxCount)
}

// GetHeadHash mocks base method.
func (m *MockGitClient) GetHeadHash(dir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeadHash", dir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeadHash indicates an expected call of GetHeadHash.
func (mr *MockGitClientMockRecorder) GetHeadHash(dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeadHash", reflect.TypeOf((*MockGitClient)(nil).GetHeadHash), dir)
}

// Init mocks base method.
func (m *MockGitClient) Init(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockGitClientMockRecorder) Init(dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockGitClient)(nil).Init), dir)
}

// ListTree mocks base method.
func (m *MockGitClient) ListTree(dir, ref, subdir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTree", dir, ref, subdir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTree indicates an expected call of ListTree.
func (mr *MockGitClientMockRecorder) ListTree(dir, ref, subdir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTree", reflect.TypeOf((*MockGitClient)(nil).ListTree), dir, ref, subdir)
}
