package core

// GeneratePreCommitHook returns a POSIX shell script for a pre-commit
// vendor compliance guard. The script calls `git-vendor status --offline`
// and blocks commits on strict drift (exit 1). Lenient drift (exit 2)
// prints a warning but allows the commit. Info drift (exit 0) passes
// silently.
//
// GeneratePreCommitHook produces a simplified, standalone alternative to
// the full vendor-guard.sh (which adds two-pass staleness checks and
// policy-aware gating). Projects can upgrade to the full hook later.
func GeneratePreCommitHook() string {
	return `#!/bin/sh
# Generated by: git-vendor hook install --pre-commit
# Vendor compliance guard — blocks commits with strict vendor drift.
# Exit codes from git-vendor status:
#   0 = PASS (no drift, or info-only)
#   1 = FAIL (strict vendor drift — commit blocked)
#   2 = WARN (lenient vendor drift — warning only)

# Skip if git-vendor is not installed
if ! command -v git-vendor >/dev/null 2>&1; then
    exit 0
fi

# Skip if not a vendored project
if [ ! -f ".git-vendor/vendor.yml" ]; then
    exit 0
fi

OUTPUT=$(git-vendor status --offline --quiet 2>&1)
EXIT_CODE=$?

if [ "$EXIT_CODE" -eq 0 ]; then
    exit 0
fi

if [ "$EXIT_CODE" -eq 2 ]; then
    echo "[git-vendor] Vendor drift detected (lenient — warning only):" >&2
    echo "$OUTPUT" >&2
    echo "" >&2
    echo "Resolve with:" >&2
    echo "  git vendor pull     # restore upstream files" >&2
    echo "  git vendor push     # propose changes upstream" >&2
    echo "  git vendor accept   # acknowledge drift" >&2
    exit 0
fi

echo "[git-vendor] Vendor compliance check failed (strict):" >&2
echo "$OUTPUT" >&2
echo "" >&2
echo "Resolve with:" >&2
echo "  git vendor pull     # restore upstream files" >&2
echo "  git vendor push     # propose changes upstream" >&2
echo "  git vendor accept   # acknowledge drift" >&2
echo "" >&2
echo "Commit blocked." >&2
exit 1
`
}

// GenerateMakefileTarget returns a Makefile snippet with a ` + "`vendor-check`" + `
// phony target that calls ` + "`git-vendor status --offline --strict-only --quiet`" + `.
// Only strict enforcement failures block the build (lenient/info pass).
func GenerateMakefileTarget() string {
	return `.PHONY: vendor-check
vendor-check:
	@git-vendor status --offline --strict-only --quiet || \
		(echo "Strict vendor compliance failed" && exit 1)
`
}
